<?php

/**
 * @file
 * Contains selectra.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function selectra_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the selectra module.
    case 'help.page.selectra':
      $output = '';
      $output .= '<h3>' . t('Selectra') . '</h3>';
      $output .= '<p>' . t('Sample module to start with') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function selectra_theme() {
  return [
    'selectra' => [
      'variables' => [
        'pdf_file' => NULL,
      ],
    ],
  ];
}

